[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = bodmer/TFT_eSPI
build_flags =
  -DUSER_SETUP_LOADED=1
  -DLOAD_GLCD=1
  -DGC9A01_DRIVER
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=17
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_MISO=-1
  -DTOUCH_CS=-1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=240
  -DSPI_FREQUENCY=27000000
  -DSPI_READ_FREQUENCY=16000000

[env:v1]
extends = common
src_filter = +<v1/*.cpp>

[env:v2]
extends = common
src_filter = +<v2/*.cpp>

[env:v3]
extends = common
src_filter = +<v3/*.cpp>

[env:v4]
extends = common
src_filter = +<v4/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =

[env:v5]
extends = common
src_filter = +<v5/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =

[env:v6]
extends = common
src_filter = +<v6/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v7]
extends = common
src_filter = +<v7/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v7_bis]
extends = common
src_filter = +<v7/bis/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v8]
extends = common
src_filter = +<v8/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v9]
extends = common
src_filter = +<v9/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v7_night]
extends = common
src_filter = +<v7_night/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200

[env:v7_day]
extends = common
src_filter = +<v7_day/*.cpp>
lib_deps = lovyan03/LovyanGFX
build_flags =
upload_speed = 115200
